export const OBTENER_PREGUNTAS = 'OBTENER_PREGUNTAS';
export const GUARDAR_PREGUNTAS = 'GUARDAR_PREGUNTAS';
export const RESET_PREGUNTAS = 'RESET_PREGUNTAS';
export const GUARDAR_PUNTUACION = 'GUARDAR_PUNTUACION';
export const RESET_PUNTUACION = 'RESET_PUNTUACION';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const RESET_USUARIO = 'RESET_USUARIO';

export const AGREGAR_JUGADOR = 'AGREGAR_JUGADOR';
export const OBTENER_JUGADORES = 'OBTENER_JUGADORES';
